services:
  - type: web
    name: voicesentinel-forensic
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: standard # Recommended for PyTorch, uses 2GB RAM. If you change to 'free', the app may run out of memory.
    envVars:
      - key: MONGO_URI
        sync: false # You must set this manually in the Render Dashboard -> Environment Variables
      - key: USE_MOCK_DB
        value: "False"
      - key: ENABLE_WHISPER
        value: "False" # Bypasses the 512MB RAM cap on Free Tier
      - key: PORT
        value: "8080"
